### ISSUE TITLE
Roadmap for NEW_TOKEN utilization

### ISSUE THREAD

**Issue by gretchenfrage** [quinn-rs/quinn#2096]
Tracking issue for anyone interested in my attempt to implement NEW_TOKEN utilization. Thanks so much to Ralith and djc for the effort spent workshopping this with me so far!

Already done:

- [x] #2081
- [x] #2086
- [x] #2084
- [x] #2085
- [x] #2089

Anticipated future dependency path:

- [x] 1. #2094
- [x] 2. #2098 (depends on 1.)
- [x] 3. #2107 (depends on 2.)
- [x] 4. #2109 (depends on 2.)
- [x] 5. #2110 (depends on 3, will have minor merge conflicts with 4.)
- [x] 7. #1912 (depends on 5.) (note: implementation of `BloomTokenLog` and `InMemTokenStore` can be removed from 1912 and shunted to follow-up PRs)
- [x] 8. #2136 (depends on 7.)
- [x] 9. #2137 (depends on 7, thus can be created simultaneously to 8.)

Possible future followup work:

- Allow more manual usage of tokens on client side
- Allow more manual usage of tokens on server side
  - Allow encrypted application data to be placed in token

**Comment by gretchenfrage** [comment]
We did it!
