### ISSUE TITLE
Documentation - Examples Tracking Issue

### ISSUE THREAD

**Issue by TimonPost** [quinn-rs/quinn#890]
This issue describes the various examples that would be useful to have for Quinn. It belongs to a bigger overall documentation project as described here: #861.

# Todo

# Ideas

Various examples will be covered in the book. 

- [ ] Simple Send, Receive example with a unidirectional stream. 
- [ ] Simple Send, Receive example with a bidirectional stream. 
- [ ] Simple Send, Receive example with unreliable transport.
- [ ] Simple example demonstrating how to build a certificate.

**Comment by TimonPost** [comment]
After trying to get an example for my self together. I got two main remarks:

- I have a hard time finding an easy example I can just copy and paste from. Examples like simple sending, receiving, using different stream types. I think it would be useful to add more simplistic examples to this library. What do you think?
- The async code makes it really difficult to see what the examples do. I can not inspect what kind of types are returned. My idea doesn't support this yet. Are there ideas that do support this?
